#####################################################################################
#                                                                                   #
#                               General Configurations                              #
#                                                                                   #
#####################################################################################

# language file to use (feel free to add your own lang file within the lang folder of the plugin and put the name here)
lang-file: 'en.yml'

# if true, will hide all players on join (i.e. playerhide toggled on during
hide-on-join: false

# particles can be used from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# set to "NONE" for complete invisibility
particles: "NONE"
# number of particles shown, does nothing if particles is set to "NONE"
particle-count: 3

#####################################################################################
#                                                                                   #
#                                 Item Configurations                               #
#                                                                                   #
#####################################################################################

item-on-join: true
allow-drop: false
allow-move: false

item:
  name: "&aMostrando a todos &8» &fClick para cambiar"
  slot: 5
  material: LIME_DYE
  sound: ENTITY_ARMADILLO_EAT;100;3
  enchanted: false
  lore:
    - ""

item-toggled-on:
  disabled: false
  name: "&7Ocultando a todos &8» &fClick para cambiar"
  slot: 5
  sound: ENTITY_ARMADILLO_EAT;100;3
  material: GRAY_DYE
  enchanted: false
  lore:
    - ""

#####################################################################################
#                                                                                   #
#            Section for PAPI placeholders (ignore section if not using)            #
#                                                                                   #
#####################################################################################

# currently supports 1 PAPI placeholder as shown below
# %phide_player_status% - current state of player (defined in en.yml - visible-state/hidden-state)
