#####################################################################################
#                                                                                   #
#                               General Configurations                              #
#                                                                                   #
#####################################################################################

# language file to use (feel free to add your own lang file within the lang folder of the plugin and put the name here)
lang-file: 'en.yml'

# if true, will hide all players on join (i.e. playerhide toggled on during
hide-on-join: true

# particles can be used from https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Particle.html
# set to "NONE" for complete invisibility
particles: "NONE"
# number of particles shown, does nothing if particles is set to "NONE"
particle-count: 3

#####################################################################################
#                                                                                   #
#                                 Item Configurations                               #
#                                                                                   #
#####################################################################################

# provide item for player to toggle visibility on join
item-on-join: true

# allow players to drop the item
allow-drop: false

# allow players to move the item
allow-move: false

# material, name, slot of item and whether item should be enchanted
item:
  name: "&bPlayerHide Stick"
  slot: 0
  material: STICK
  enchanted: false
  lore:
    - "&6Right click &ato toggle on!"

# optional item that is shown when playerhide is toggled on (i.e. players are hidden)
# if disabled, will only use the item defined above
item-toggled-on:
  disabled: false
  name: "&bPlayerHide Stick"
  slot: 0
  material: STICK
  enchanted: true
  lore:
    - "&6Right click &ato toggle off!"

#####################################################################################
#                                                                                   #
#            Section for PAPI placeholders (ignore section if not using)            #
#                                                                                   #
#####################################################################################

# currently supports 1 PAPI placeholder as shown below
# %phide_player_status% - current state of player (defined in en.yml - visible-state/hidden-state)
