name: PlayerHide
version: ${project.version}
main: tk.taverncraft.playerhide.Main
author: tjtanjin - FrozenFever
description: A simple plugin for hiding players
api-version: 1.13
softdepend: [WorldEdit, WorldGuard]
commands:
  playerhide:
    description: Base command for the plugin
    aliases: [phide]
permissions:
  phide.help:
    description: View the list of commands
    default: op
  phide.toggle.self:
    description: Toggle self visibility of other players
    default: op
  phide.toggle.others:
    description: Toggle a specific player's visibility of other players
    default: op
  phide.reload:
    description: Reload the plugin
    default: op